### ISSUE TITLE
Name of the Hackathons

### ISSUE THREAD

**Issue by rajarshimaitra** [B4I-Technical-Track/party-layout#4]
We need to come up sleek name. Refs https://bolt.fun/

Throw down same of your fav names below.. The more degen it is the better.. 😄

**Comment by sandipndev** [comment]
- Bitcoin Hackathon
- Bitcoin Hack
- Bitcoin Bootstrap/Inception/CodeJam

**Comment by sandipndev** [comment]
@shreyan: Moneyhack

**Comment by rajarshimaitra** [comment]
Hack A Bit..

**Comment by rajarshimaitra** [comment]
We Finalized on MoneyHack.. LFG..
